### ISSUE TITLE
distribute on conda-forge?

### ISSUE THREAD

**Issue by bollwyvl** [jupyterlab-contrib/jupyterlab-tour#10]
I see _Install_ in the README suggests this is available on `conda-forge`, but I [don't see it](https://anaconda.org/conda-forge/jupyterlab-tour). Happy to start it up, and/or add any other co-maintainers!

**Comment by fcollonval** [comment]
conda package is now available :tada:

**Comment by bollwyvl** [comment]
Hooray, I'll be testing today!
