### ISSUE TITLE
step changed

### ISSUE THREAD

**Issue by djangoliv** [jupyterlab-contrib/jupyterlab-tour#31]
I am creating a tour for my extension:

```
export const myTour = {
  id: "example",
  label: "example",
  hasHelpEntry: true,
  steps: [{
      content: (<p>1st step </p>),
      placement: "center",
      target: "#jp-main-dock-panel",
      title: "MyTitle",
    },
    {
      content: (<p> 2sd step </p>),
      placement: "right",
      target: "#hiddenId",
      title: i18next.t("My title"),
    },
  ],
};
```

I works fine, but I can't see how I can add a `stepChanged` (like it's done for the #FileBrowser in the welcome tour) if the target of the second step is hidden.

Regards

**Comment by fcollonval** [comment]
Thanks for the interest @djangoliv 

For now there is no easy way of doing that. But from your snippet, I see you are defining the tour from the code extension. So 

1. You need to request `ITourManager` token for your jupyterlab extension; like this:

https://github.com/jupyterlab-contrib/jupyterlab-tour/blob/d142ca95f5a2d355f6dd2c5689bc879ec84fab52/src/plugin.tsx#L147-L159

2. Assuming `myTour` is defined as in your snippet, create the tour handler object:

```ts
const myTourHandler = tourManager.addTour(myTour);
```

3. Add callback on `stepChanged`:

```ts
myTourHandler.stepChanged.connect((_, data) => {
  switch (data.type) {
    case 'step:after':
      if (data.step.target === '.jp-SideBar.jp-mod-left') {
        commands.execute('filebrowser:activate');
      } else if (data.step.target === '#filebrowser') {
        commands.execute('apputils:activate-command-palette');
      }
      break;
  }
});
```

**Comment by djangoliv** [comment]
Nice, it works. Thanks !
