### ISSUE TITLE
close notebook after the notebook tour

### ISSUE THREAD

**Issue by djangoliv** [jupyterlab-contrib/jupyterlab-tour#32]
After the notebook tour, the example notebook is still open. I think it could be nice to close and delete this notebook to recover the initial state of jupyterlab .

Regards

**Comment by fcollonval** [comment]
Nice suggestion

**Comment by djangoliv** [comment]
Here a PR for this issue: https://github.com/jupyterlab-contrib/jupyterlab-tour/pull/34

**Comment by fcollonval** [comment]
Fixed by #34
