### ISSUE TITLE
[high-priority] some observations with jupyterlab 3.1.0b0

### ISSUE THREAD

**Issue by bollwyvl** [jupyterlab-contrib/jupyterlab-tour#39]
Some issues over on the draft PR https://github.com/jtpio/jupyterlite/pull/207, seeing this when trying to add new tours:

![Screenshot from 2021-07-02 21-19-24](https://user-images.githubusercontent.com/45380/124339284-8b550f80-db7b-11eb-984f-9e148036af50.png)

> this can be observed in the [demo](https://jupyterlite--207.org.readthedocs.build/en/207/_static/lab/index.html)

Very much a work in progress over there, so no :fire: !

If i can swing the time I'll try to work up (at least) a reproducer over here... but don't want to make busywork for anybody, since i'm sure some of these APIs might change _again_...

**Comment by jtpio** [comment]
To remove JupyterLite out of the equation, I quickly tested with this gist and `jupyterlab==3.1.0b0` and it also seems to be happening on Binder:

- https://gist.github.com/jtpio/c54863279a09e6f2cd2c0216d55df5c2
- https://mybinder.org/v2/gist/jtpio/c54863279a09e6f2cd2c0216d55df5c2/master?urlpath=/lab

![image](https://user-images.githubusercontent.com/591645/124751529-05441a80-df27-11eb-8457-f911d2ca8dd8.png)

This looks like something that we should fix upstream, as we don't want folks to update their extensions for 3.1.

**Comment by bollwyvl** [comment]
right: folk should update when they _want_ the carrot (like collaborative editing and better license compliance... guess latter's kind of a crappy carrot :shrug:) but not the stick of _my install instructions don't work for my users AWOONGA AWOONGA_... or just bounce because we can't ship software people can build on.

**Comment by fcollonval** [comment]
Thanks both. Indeed something needs to be solved upstream. I'll push a fix (thanks for the trace - you nail the source).

**Comment by fcollonval** [comment]
Coding this one as the fix has been pushed in JupyterLab

**Comment by jtpio** [comment]
Nice. Will check with the next beta release to confirm. Thanks for the fix!

**Comment by jtpio** [comment]
Update the gist with `3.1.0cr1` and it looks good on Binder :+1:

**Comment by bollwyvl** [comment]
Thanks all!
