### ISSUE TITLE
Split the default tours into multiple plugins

### ISSUE THREAD

**Issue by jtpio** [jupyterlab-contrib/jupyterlab-tour#40]
## Is your feature request related to a problem? Please describe.

This was originally discussed in https://github.com/jupyterlite/jupyterlite/pull/287#issuecomment-885156090.

Where RetroLab doesn't handle the default welcome tour, but the notebook tour works out of the box.

## Describe the solution you'd like

Maybe this logic could be split so the tours are added in separate plugins?

https://github.com/jupyterlab-contrib/jupyterlab-tour/blob/bc979d7929d5f141e24b6eeb7620959a2c5276e3/src/defaults.tsx#L487-L495

Or switch to using the settings-based way for defining tours for the defaults as well?

## Describe alternatives you've considered

The plugin adding defaults could be disabled, and tours recreated manually.

## Additional context

- Python package version: 3.1.2

- Extension version: 3.1.2

- Operating System and its version: Ubuntu 20.04

**Comment by fcollonval** [comment]
Those tours are more complicated as they interact with the UI. They cannot move to the settings.

I am not sure splitting them in multiple plugins is a good path as (I hope) the number of default tours will increase.

What about having a setting that select which default tours will be activated?
