### ISSUE TITLE
Support JupyterLab 4, Notebook 7

### ISSUE THREAD

**Issue by bollwyvl** [jupyterlab-contrib/jupyterlab-tour#76]
## Is your feature request related to a problem? Please describe.

This package doesn't have an upper bound on its jupyterlab, but also doesn't support JupyterLab 4

## Describe the solution you'd like

a new release line that _only_ supports JupyterLab 4/Notebook 7

## Describe alternatives you've considered

a release that supports JupyterLab 3 and JupyterLab 4 and Notebook 7. This is probably harder.

## Additional context

It would be nice to get #29 into it, but wouldn't strictly be blocking.

**Comment by jtpio** [comment]
While it might be working in JupyterLab 4 and Notebook 7, looks like we lost JupyterLite support on the way: https://github.com/jupyterlab-contrib/jupyterlab-tour/pull/81#issuecomment-1832268381

**Comment by jtpio** [comment]
Opened https://github.com/jupyterlab-contrib/jupyterlab-tour/issues/82
