### ISSUE TITLE
Version 4.0.0 breaks JupyterLite support

### ISSUE THREAD

**Issue by jtpio** [jupyterlab-contrib/jupyterlab-tour#82]
## Description

As noticed in https://github.com/jupyterlite/jupyterlite/pull/1258#issuecomment-1832257180 and https://github.com/jupyterlab-contrib/jupyterlab-tour/issues/76#issuecomment-1832269959, the new JupyterLab 4 compatible version does not seem to work

## Reproduce

For example testing with ReadTheDocs preview for https://github.com/jupyterlite/jupyterlite/pull/1258: https://jupyterlite--1258.org.readthedocs.build/en/1258/_static/lab/index.html

## Expected behavior

`jupyterlab-tour` was running fine with JupyterLite before.

Looks like this might be related to some new server side logic introduced recently in https://github.com/jupyterlab-contrib/jupyterlab-tour/pull/81? Could this be made optional to keep JupyterLite support?

**Comment by fcollonval** [comment]
The latest version is now using the `api/config` [endpoint](https://petstore.swagger.io/?url=https://raw.githubusercontent.com/jupyter/jupyter_server/master/jupyter_server/services/api/api.yaml#/config) from Jupyter Server to store the tours seen independently of the workspaces.

From the demo 1258 you are linking I see the tours are working. I guess the _fix_ should be on Lite to implement the handling of the standard _config_ REST endpoint.

**Comment by jtpio** [comment]
JupyterLite does not implement all the Jupyter Server endpoints (for example there is no `api/terminals` or `api/me`) Up until now `api/config` has not been needed. So I was wondering if there could be way to get away without having to implement it, just like it was the case with the previous version of `jupyterlab-tour`.

> store the tours seen independently of the workspaces.

What issue does this cause?

**Comment by jtpio** [comment]
> From the demo 1258 you are linking I see the tours are working.

They seem to be working but only partially?

For example the tours are not in the command palette anymore:

![image](https://github.com/jupyterlab-contrib/jupyterlab-tour/assets/591645/e1cdb30c-13a1-40bb-8353-27cc0e14fc60)

And they seem to be greyed out afterwards in the help menu:

![image](https://github.com/jupyterlab-contrib/jupyterlab-tour/assets/591645/78180e90-a6bd-431b-985e-1a48e9f36319)

**Comment by EwoutH** [comment]
Hi! I would love to be able to use this again! Is there any news on this issue?

**Comment by jtpio** [comment]
@EwoutH the latest versions of `jupyterlab-tour` and `jupyterlite` should now work together, which is the case on the demo repo: https://jupyterlite.readthedocs.io/en/stable/_static/lab/index.html

Closing this issue as fixed, but don't hesitate to comment or open a new one if you still have issues, thanks!
